import js from '@eslint/js'
import { defineConfig } from 'eslint/config'
import tseslint from 'typescript-eslint'
import stylistic from '@stylistic/eslint-plugin'

export default defineConfig(
  // Global ignore — gitignored build output (regenerated by `build-storybook`) isn't excluded
  // by the `files: ['src/**/*.ts']` glob below the way a top-level `ignores` entry is; without
  // this, `eslint .` still discovers and lints the minified bundle if it happens to exist
  // locally, hitting rule-definition errors for plugins that aren't configured for it.
  { ignores: ['storybook-static/**'] },
  {
    files: ['src/**/*.ts'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      stylistic.configs.customize({ indent: 2, quotes: 'single', semi: false }),
    ],
  },
)
